import { Platform, StyleSheet } from "react-native";
import { Color, Font } from "../../constants/GlobalStyle";

export const summeryStyle = StyleSheet.create({
  headerContainer: {
    height: 70,
    alignItems: "center",
    flexDirection: "row",
    paddingHorizontal: 20,
    borderBottomColor: Color.C_H_black,
    borderBottomWidth: 1,
  },
  title: { fontSize: Font.Font_L, fontWeight: "600" },
  topSummeryBox: {
    width: "90%",
    alignSelf: "center",
    borderRadius: 15,
    shadowColor: Color.C_H_black,
    elevation: 15,
    backgroundColor: Color.C_white,
    marginBottom: 20,
    padding: 20,
    shadowOffset: {
      width: 2,
      height: 1,
    },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  summeryTitle: {
    fontSize: Font.Font_X,
    fontWeight: "600",
    marginBottom: 20,
  },
  summeryItemBox: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: 15,
  },
  borderBottomStyle: {
    borderStyle: Platform.OS === "ios" ? "solid" : "dashed",
    borderBottomWidth: 1,
    borderBottomColor: Color.C_border,
  },

  summeryItemNormalText: { fontSize: Font.Font_L, color: "rgba(0,0,0,0.7)" },
  summeryItemSmallText: { fontSize: Font.Font_S, color: "rgba(0,0,0,0.4)" },
  summeryItemCurrency: {
    fontSize: Font.Font_M,
    fontWeight: "500",
    color: "rgba(0,0,0,0.8)",
  },
  grandTotalCon: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 20,
  },
  summeryCurrency: {
    fontSize: Font.Font_M,
    fontWeight: "800",
    color: "#7F35CD",
  },
  shiptoBox: {
    borderRadius: 15,
    width: "90%",
    alignSelf: "center",
    shadowColor: Color.C_H_black,
    elevation: 15,
    backgroundColor: Color.C_white,
    padding: 20,
    shadowOffset: {
      width: 2,
      height: 1,
    },
    shadowRadius: 5,
    shadowOpacity: 0.2,
  },
  shipToItem: {
    flexDirection: "row",
    alignItems: "center",
    height: 40,
    // backgroundColor: "red",
  },
  shipToText: {
    fontSize: Font.Font_M,
    color: "rgba(0,0,0,0.7)",
  },
  shipToItemText: {
    fontSize: Font.Font_M,
    color: "rgba(0,0,0,0.8)",
    marginLeft: 5,
  },
  emptyRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Color.C_border,
  },
  nameInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  nameInput: {
    height: 40,
    borderRadius: 8,
    paddingHorizontal: 10,
    fontSize: 18,
    flex: 1,
    borderColor: Color.C_border,
    borderWidth: 1,
  },
  inputBox: {
    borderWidth: 1,
    borderColor: Color.C_border,
    borderRadius: 10,
    height: 40,
    width: "100%",
    marginTop: 14,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 10,
  },
  inputText: {
    fontSize: Font.Font_M,
    color: "rgba(0,0,0,0.4)",
  },
  numberInput: {
    height: 40,
    borderRadius: 8,
    paddingHorizontal: 10,
    fontSize: 18,
    width: "100%",
    borderColor: Color.C_border,
    borderWidth: 1,
    marginTop: 14,
  },
  nextButton: {
    backgroundColor: "red",
    height: 50,
    position: "absolute",
    bottom: 20,
    width: "90%",
    alignSelf: "center",
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonText: {
    color: Color.C_white,
    fontSize: Font.Font_L,
    fontWeight: "600",
  },
});
